### ISSUE TITLE
发起语音会调用摄像头的问题

### ISSUE THREAD

**Issue by milesking** [comsince/vue-chat#2]
发起语音会调用摄像头，看了一下前端代码发现voipclient.js所有this.currentSession.isAudioOnly应该都是this.currentSession.audioOnly。这时候挂断报错 "TypeError: this.webcamStream.getTracks.forEach is not a function"，看起来是个set用forEach没毛病啊。

**Comment by comsince** [comment]
this.currentSession.audioOnly 的确是currentsession里面的参数写错了，你说的报错，是每次语音必现吗

**Comment by milesking** [comment]
> this.currentSession.audioOnly 的确是currentsession里面的参数写错了，你说的报错，是每次语音必现吗
替换好this.currentSession.audioOnly单独发起语音，然后自己挂断或者对方挂断都有：debug发现这时候this.webcamStream.getTracks长度是0，不知道是不是我改第一个问题导致的。

**Comment by milesking** [comment]
我不小心解决了，抄了video的逻辑，把注释中的代码替换掉：
/*              this.webcamStream.getTracks.forEach(
                track => {
                  track.stop();
                }
              )*/
              var localAudio = document.getElementById("wxCallLocalAudio");
              if (localAudio.srcObject) {
                localAudio.pause();
                localAudio.srcObject.getTracks().forEach(track => {
                  track.stop();
                });
              }

**Comment by comsince** [comment]
可能现在代码里面currentsesion里面的参数使用错误，导致video始终为true,
这段代码/* this.webcamStream.getTracks.forEach(
track => {
track.stop();
}
)*/ 貌似都没有执行过，你的改动按照video的方式，应该没有问题，谢谢帮忙发现问题

**Comment by milesking** [comment]
还有一段this.webcamStream.getTracks.forEach也是有问题的，this.webcamStream长度始终是0，不知道是不是赋值的地方调用的await的问题。然后我改完之后挂断语音，可以挂断但是浏览器的语音还是处于正在使用状态，WebRTC这块实在不懂了
