### ISSUE TITLE
这个项目后续会不会添加Election桌面应用程序，不然用起来很难受啊？

### ISSUE THREAD

**Issue by Yossarian161** [comsince/vue-chat#3]

**Comment by comsince** [comment]
目前功能还在完善中，你说的用起来难受 ，是指哪方面？

**Comment by Yossarian161** [comment]
就是没有客户端的话，浏览器一关就没了，而且不像微信客户端，底部有消息闪烁提示功能。

**Comment by comsince** [comment]
这个目前还没有考虑，如果你对这个比较熟悉的话，建议可以帮我实现一下，我现在主要还是在完善功能，修复bug,可能目前没有精力，关于使用体验的问题，估计还得最后考虑

**Comment by comsince** [comment]
桌面程序已经发布,详见:https://fsharechat.cn/getstarted/
